name: Tail cyber.gc.ca logs

on:
  workflow_dispatch:
  schedule:
    - cron: '27 * * * *'

permissions:
  contents: write

jobs:
    tail-canada-ca-logs:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: Tail cyber.gc.ca logs
          uses: maxneuvians/tail-ct-log-action@main
          env:
            DOMAIN: "cyber.gc.ca"

        - name: Check for changes
          id: git_diff
          run: |
            git fetch origin main
            git diff --exit-code origin/main || echo "changes"

        - name: Commit files
          if: steps.git_diff.outputs.changes == 'changes'
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "Work bot"
            git add -A
            git commit -m "Adding cyber.gc.ca logs `date '+%Y-%m-%d %H:%M:%S'`" -a
            git push origin main