name: Check DNS records for hijacking

on:
  workflow_dispatch:

jobs:
    check-dns-records:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: Concatenate JSONL files
          run: |
            cat *.jsonl > combined.jsonl

        - name: Convert JSONL logs to JSON
          run: |
            jq -r '.domain' combined.jsonl | sort | uniq > domains.txt

        - name: Check DNS records
          uses: maxneuvians/dns-hijack-check-action@main

        - name: Get length of critical domains and save in output
          id: critical_domains
          run: |
            echo "critical_domains=$(jq 'length' critical.json)" >> $GITHUB_OUTPUT

        - name: Upload critical domains
          id: upload_critical_domains
          if: steps.critical_domains.outputs.critical_domains > 0
          uses: actions/upload-artifact@v4
            with:
              name: critical-domains
              path: critical.json
              retention-days: 1


        - name: Send email if critical domains found
          if: steps.critical_domains.outputs.critical_domains > 0
          uses: cds-snc/gc-notification-github-action@main
          env:
            BODY: '{"subject": "${{ steps.critical_domains.outputs.critical_domains }} vulnerable domains found", "body": "[View domain list]${{ steps.upload_critical_domains.outputs.artifact-url }}"}'
          with:
            api-key: ${{ secrets.NOTIFY_API_KEY }}
            personalisation: ${{ env.BODY }}
            recipient: max@neuvians.net
            template-id: ${{ secrets.NOTIFY_EMAIL_TEMPLATE_ID }}