name: Tail matrix logs

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

permissions:
  contents: write

jobs:
  tail-logs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain: ['agr.gc.ca', 'pco.gc.ca', 'pm.gc.ca', 'science.gc.ca', 'statcan.gc.ca']
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Tail logs for ${{ matrix.domain }}
        uses: maxneuvians/tail-ct-log-action@main
        env:
          DOMAIN: ${{ matrix.domain }}

      - name: Check for changes
        id: git_diff
        run: |
          git fetch origin main
          git diff --exit-code origin/main || echo "changes=changes" >> $GITHUB_OUTPUT

      - name: Commit files
        if: steps.git_diff.outputs.changes == 'changes'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Work bot"
          git add -A
          git commit -m "Adding ${{ matrix.domain }} logs `date '+%Y-%m-%d %H:%M:%S'`" -a
      
      - name: Pull latest changes
        if: steps.git_diff.outputs.changes == 'changes'
        run: git pull --rebase origin main

      - name: Push changes
        if: steps.git_diff.outputs.changes == 'changes'
        run: git push origin main